### ISSUE TITLE
Sequel and fixtures, oh my!

### ISSUE THREAD

**Issue by onewheelskyward** [adamdavis40208/sequel-test#1]
Hey, I'm a friend of @samkeen, I wanted to share with you how we do fixtures in Sequel.  The repo is private but we use Sqlite in-memory DB in test mode and use @jeremyevans' excellent fixture gem to handle seed data.

 http://sequel.jeremyevans.net/rdoc/files/doc/cheat_sheet_rdoc.html#label-Open+an+SQLite+memory+database  
https://github.com/jeremyevans/fixture_dependencies

Let me know if you have any trouble implementing!

**Comment by adamdavis40208** [comment]
No problem at all -- very slick how you can pull them into tests, I really like that. I went with sequel:seed on db:migrate, but used the fixture loader in tests. Thanks for the tip!
